POST http://localhost:3000/students
Content-Type: application/json

{
  "first_name": "Yoad",
  "last_name": "Azani",
  "id": "208389403",
  "class": "A3110",
  "trend": "programing"
}

###

PUT http://localhost:3000/students/316514257
Content-Type: application/json

{
  "first_name": "Avi",
  "last_name": "Cohen",
  "id": "316514257",
  "class": "A3110",
  "trend": "programing"
}

###

DELETE http://localhost:3000/students/316514257
Content-Type: application/json

###

GET http://localhost:3000/students
Accept: application/json